# Buildpack ID and metadata
[buildpack]
id = "com.xprettyjohns.buildpacks.ssh"
version = "0.0.1"
name = "SSH Buildpack"

# Stacks that the buildpack will work with
[[stacks]]
id = "heroku-18"

[[stacks]]
id = "io.buildpacks.stacks.bionic"

[[stacks]]
id = "io.buildpacks.stacks.cflinuxfs3"
